# CMake generated Testfile for 
# Source directory: /home/naeper/work/python-cellframe
# Build directory: /home/naeper/work/python-cellframe/build_debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_unit "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/home/naeper/work/python-cellframe/venv_test/lib/python3.11/site-packages:/home/naeper/work/python-cellframe:/home/naeper/work/python-cellframe/build_debug:" "LD_LIBRARY_PATH=/home/naeper/work/python-cellframe/build_debug:/home/naeper/work/python-cellframe/build_debug/dap-sdk-build:/home/naeper/work/python-cellframe/build_debug/cellframe-sdk-embedded:/home/naeper/work/python-cellframe/build_debug/python-dap:/tmp/.mount_Cursorpe6nJt/usr/lib/:/tmp/.mount_Cursorpe6nJt/usr/lib32/:/tmp/.mount_Cursorpe6nJt/usr/lib64/:/tmp/.mount_Cursorpe6nJt/lib/:/tmp/.mount_Cursorpe6nJt/lib/i386-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib/x86_64-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib/aarch64-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib32/:/tmp/.mount_Cursorpe6nJt/lib64/:/tmp/.mount_CursoruphvQv/usr/lib/:/tmp/.mount_CursoruphvQv/usr/lib32/:/tmp/.mount_CursoruphvQv/usr/lib64/:/tmp/.mount_CursoruphvQv/lib/:/tmp/.mount_CursoruphvQv/lib/i386-linux-gnu/:/tmp/.mount_CursoruphvQv/lib/x86_64-linux-gnu/:/tmp/.mount_CursoruphvQv/lib/aarch64-linux-gnu/:/tmp/.mount_CursoruphvQv/lib32/:/tmp/.mount_CursoruphvQv/lib64/:" "CELLFRAME_TEST_MODE=1" "DAP_SDK_TEST_MODE=1" "/home/naeper/work/python-cellframe/venv_test/bin/python3" "-m" "pytest" "unit/" "-v" "--tb=short")
set_tests_properties(test_unit PROPERTIES  DEPENDS "python_cellframe" RUN_SERIAL "TRUE" TIMEOUT "600" WORKING_DIRECTORY "/home/naeper/work/python-cellframe/tests" _BACKTRACE_TRIPLES "/home/naeper/work/python-cellframe/CMakeLists.txt;407;add_test;/home/naeper/work/python-cellframe/CMakeLists.txt;433;add_pytest_test;/home/naeper/work/python-cellframe/CMakeLists.txt;0;")
add_test(test_unit_legacy "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/home/naeper/work/python-cellframe/venv_test/lib/python3.11/site-packages:/home/naeper/work/python-cellframe:/home/naeper/work/python-cellframe/build_debug:" "LD_LIBRARY_PATH=/home/naeper/work/python-cellframe/build_debug:/home/naeper/work/python-cellframe/build_debug/dap-sdk-build:/home/naeper/work/python-cellframe/build_debug/cellframe-sdk-embedded:/home/naeper/work/python-cellframe/build_debug/python-dap:/tmp/.mount_Cursorpe6nJt/usr/lib/:/tmp/.mount_Cursorpe6nJt/usr/lib32/:/tmp/.mount_Cursorpe6nJt/usr/lib64/:/tmp/.mount_Cursorpe6nJt/lib/:/tmp/.mount_Cursorpe6nJt/lib/i386-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib/x86_64-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib/aarch64-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib32/:/tmp/.mount_Cursorpe6nJt/lib64/:/tmp/.mount_CursoruphvQv/usr/lib/:/tmp/.mount_CursoruphvQv/usr/lib32/:/tmp/.mount_CursoruphvQv/usr/lib64/:/tmp/.mount_CursoruphvQv/lib/:/tmp/.mount_CursoruphvQv/lib/i386-linux-gnu/:/tmp/.mount_CursoruphvQv/lib/x86_64-linux-gnu/:/tmp/.mount_CursoruphvQv/lib/aarch64-linux-gnu/:/tmp/.mount_CursoruphvQv/lib32/:/tmp/.mount_CursoruphvQv/lib64/:" "CELLFRAME_TEST_MODE=1" "DAP_SDK_TEST_MODE=1" "/home/naeper/work/python-cellframe/venv_test/bin/python3" "-m" "pytest" "unit/legacy/" "-v" "--tb=short")
set_tests_properties(test_unit_legacy PROPERTIES  DEPENDS "python_cellframe" RUN_SERIAL "TRUE" TIMEOUT "600" WORKING_DIRECTORY "/home/naeper/work/python-cellframe/tests" _BACKTRACE_TRIPLES "/home/naeper/work/python-cellframe/CMakeLists.txt;407;add_test;/home/naeper/work/python-cellframe/CMakeLists.txt;434;add_pytest_test;/home/naeper/work/python-cellframe/CMakeLists.txt;0;")
add_test(test_unit_composer "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/home/naeper/work/python-cellframe/venv_test/lib/python3.11/site-packages:/home/naeper/work/python-cellframe:/home/naeper/work/python-cellframe/build_debug:" "LD_LIBRARY_PATH=/home/naeper/work/python-cellframe/build_debug:/home/naeper/work/python-cellframe/build_debug/dap-sdk-build:/home/naeper/work/python-cellframe/build_debug/cellframe-sdk-embedded:/home/naeper/work/python-cellframe/build_debug/python-dap:/tmp/.mount_Cursorpe6nJt/usr/lib/:/tmp/.mount_Cursorpe6nJt/usr/lib32/:/tmp/.mount_Cursorpe6nJt/usr/lib64/:/tmp/.mount_Cursorpe6nJt/lib/:/tmp/.mount_Cursorpe6nJt/lib/i386-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib/x86_64-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib/aarch64-linux-gnu/:/tmp/.mount_Cursorpe6nJt/lib32/:/tmp/.mount_Cursorpe6nJt/lib64/:/tmp/.mount_CursoruphvQv/usr/lib/:/tmp/.mount_CursoruphvQv/usr/lib32/:/tmp/.mount_CursoruphvQv/usr/lib64/:/tmp/.mount_CursoruphvQv/lib/:/tmp/.mount_CursoruphvQv/lib/i386-linux-gnu/:/tmp/.mount_CursoruphvQv/lib/x86_64-linux-gnu/:/tmp/.mount_CursoruphvQv/lib/aarch64-linux-gnu/:/tmp/.mount_CursoruphvQv/lib32/:/tmp/.mount_CursoruphvQv/lib64/:" "CELLFRAME_TEST_MODE=1" "DAP_SDK_TEST_MODE=1" "/home/naeper/work/python-cellframe/venv_test/bin/python3" "-m" "pytest" "unit/composer/" "-v" "--tb=short")
set_tests_properties(test_unit_composer PROPERTIES  DEPENDS "python_cellframe" RUN_SERIAL "TRUE" TIMEOUT "600" WORKING_DIRECTORY "/home/naeper/work/python-cellframe/tests" _BACKTRACE_TRIPLES "/home/naeper/work/python-cellframe/CMakeLists.txt;407;add_test;/home/naeper/work/python-cellframe/CMakeLists.txt;435;add_pytest_test;/home/naeper/work/python-cellframe/CMakeLists.txt;0;")
add_test(test_quick_functionality "/usr/bin/cmake" "-E" "env" "PYTHONPATH=/home/naeper/work/python-cellframe:/home/naeper/work/python-cellframe/venv_test/lib/python3.11/site-packages:" "CELLFRAME_TEST_MODE=1" "/home/naeper/work/python-cellframe/quick_test.sh")
set_tests_properties(test_quick_functionality PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "120" WORKING_DIRECTORY "/home/naeper/work/python-cellframe" _BACKTRACE_TRIPLES "/home/naeper/work/python-cellframe/CMakeLists.txt;459;add_test;/home/naeper/work/python-cellframe/CMakeLists.txt;0;")
subdirs("dap-sdk-build")
subdirs("cellframe-sdk-embedded")
subdirs("python-dap")
