sudo: required
language: python
python:
  - "3.7-dev"
compiler: gcc
dist: xenial
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update

install: 
    - sudo apt-get install gcc make

script:
    - sudo service network-manager start
    - mkdir build
    - cd build
    - cmake -DBUILD_DAP_PYTHON_TESTS=ON ../
    - make
    - python3.7 main_test.py

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - network-manager

