sudo: required
language: cpp
compiler: gcc
dist: xenial
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update

language: python
python: 
  - "3.7-dev"

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_DAP_PYTHON_TESTS=ON ../
  - make
  - python3.7 main_test.py

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3.7-dev
    - libjson-c-dev
    - libev-dev
    - libmagic-dev
    - libldb-dev
    - libtevent-dev
    - libcurl4-gnutls-dev

