sudo: required
language: python
python:
  - "3.7-dev"
compiler: gcc
dist: xenial
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update

install: 
    - sudo apt-get install gcc make

script:
    - sudo service network-manager start
    - mkdir build
    - cd build
    - cmake
    - make
    - cp ../test/* ./
    - python3.7 main_test.py
    - python3.7 test_b58.py
    - python3.7 test_b64.py
    - python3.7 test_iaes256_cbc.py
    - python3.7 test_oaes.py


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - network-manager
