sudo: required
language: cpp
compiler: gcc
dist: xenial
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update

script:
    - sudo service network-manager start
    - mkdir build
    - cd build
    - cmake -DBUILD_DAP_PYTHON_TESTS=ON ../
    - make
    - python3.7 main_test.py

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - network-manager
    - python3.7
    - python3.7-dev
    - python3.7-minimal

