import pytest


def test_chain_sdk_exports():
    cf = pytest.importorskip("python_cellframe")

    required = [
        "dap_cert_chain_file_save",
        "dap_chain_add_callback_datum_index_notify",
        "dap_chain_add_callback_datum_removed_from_index_notify",
        "dap_chain_add_callback_notify",
        "dap_chain_add_callback_timer",
        "dap_chain_atom_add_from_threshold",
        "dap_chain_atom_confirmed_notify_add",
        "dap_chain_atom_notify",
        "dap_chain_atom_remove_notify",
        "dap_chain_atom_save",
        "dap_chain_create",
        "dap_chain_datum_notify",
        "dap_chain_datum_removed_notify",
        "dap_chain_datum_type_supported_by_chain",
        "dap_chain_deinit",
        "dap_chain_delete",
        "dap_chain_find_by_id",
        "dap_chain_generation_ban",
        "dap_chain_generation_banned",
        "dap_chain_generation_next",
        "dap_chain_get_atom_by_hash",
        "dap_chain_get_atom_last_hash",
        "dap_chain_get_atom_last_hash_num_ts",
        "dap_chain_get_blockhain_time",
        "dap_chain_get_cs_type",
        "dap_chain_get_path",
        "dap_chain_has_file_store",
        "dap_chain_id_parse",
        "dap_chain_info_dump_log",
        "dap_chain_init",
        "dap_chain_load_all",
        "dap_chain_load_from_cfg",
        "dap_chain_purge",
        "dap_chain_set_cs_name",
        "dap_chain_set_cs_type",
        "dap_chain_cell_capture_by_id",
        "dap_chain_cell_close",
        "dap_chain_cell_close_all",
        "dap_chain_cell_create",
        "dap_chain_cell_file_append",
        "dap_chain_cell_find_by_id",
        "dap_chain_cell_init",
        "dap_chain_cell_open",
        "dap_chain_cell_remit",
        "dap_chain_cell_remove",
        "dap_chain_cell_set_load_skip",
        "dap_chain_cell_truncate",
        "dap_chain_ch_deinit",
        "dap_chain_ch_init",
        "dap_stream_ch_write_error_unsafe",
        "dap_chain_ch_pkt_get_size",
        "dap_chain_ch_pkt_new",
        "dap_chain_ch_pkt_type_to_str",
        "dap_chain_ch_pkt_write",
        "dap_chain_ch_pkt_write_unsafe",
        "dap_chain_net_get_default_chain_by_chain_type",
        "dap_chain_policy_activate_json_collect",
        "dap_chain_policy_apply",
        "dap_chain_policy_create_activate",
        "dap_chain_policy_create_deactivate",
        "dap_chain_policy_deinit",
        "dap_chain_policy_get_last_num",
        "dap_chain_policy_get_size",
        "dap_chain_policy_init",
        "dap_chain_policy_is_activated",
        "dap_chain_policy_is_exist",
        "dap_chain_policy_json_collect",
        "dap_chain_policy_list",
        "dap_chain_policy_net_add",
        "dap_chain_policy_net_purge",
        "dap_chain_policy_net_remove",
        "dap_chain_policy_to_str",
        "dap_chain_policy_update_last_num",
        "dap_chain_srv_add",
        "dap_chain_srv_count",
        "dap_chain_srv_decree",
        "dap_chain_srv_deinit",
        "dap_chain_srv_delete",
        "dap_chain_srv_event_verify",
        "dap_chain_srv_fee_type_to_str",
        "dap_chain_srv_get_fees",
        "dap_chain_srv_get_internal",
        "dap_chain_srv_get_uid_by_name",
        "dap_chain_srv_hardfork_all",
        "dap_chain_srv_hardfork_complete_all",
        "dap_chain_srv_init",
        "dap_chain_srv_list",
        "dap_chain_srv_load_state",
        "dap_chain_srv_purge",
        "dap_chain_srv_purge_all",
        "dap_chain_srv_start",
        "dap_chain_srv_start_all",
    ]

    missing = [name for name in required if not hasattr(cf, name)]
    assert not missing, f"Missing chain SDK bindings: {', '.join(missing)}"
