#include "cellframe.h"

int cellframe_datum_init(PyObject *module) {
    static PyMethodDef datum_methods[] = {
        {"dap_chain_datum_calc_hash", dap_chain_datum_calc_hash_py, METH_VARARGS,
         "Calculate datum hash"},
        {"dap_chain_datum_create", dap_chain_datum_create_py, METH_VARARGS,
         "Create datum from type and data"},
        {"dap_chain_datum_dump_tx_json", dap_chain_datum_dump_tx_json_py, METH_VARARGS,
         "Dump transaction datum to JSON"},
        {"dap_chain_datum_register_dump_anchor_callback", dap_chain_datum_register_dump_anchor_callback_py, METH_VARARGS,
         "Register datum anchor JSON dump callback"},
        {"dap_chain_datum_register_dump_decree_callback", dap_chain_datum_register_dump_decree_callback_py, METH_VARARGS,
         "Register datum decree JSON dump callback"},
        {"dap_chain_datum_size", dap_chain_datum_size_py, METH_VARARGS,
         "Get datum size"},
        {"dap_chain_datum_type_id_to_str", dap_chain_datum_type_id_to_str_py, METH_VARARGS,
         "Convert datum type id to string"},
        {"dap_datum_token_dump_tsd_to_json", dap_datum_token_dump_tsd_to_json_py, METH_VARARGS,
         "Dump token TSD to JSON"},
        {"dap_chain_datum_token_flag_to_str", dap_chain_datum_token_flag_to_str_py, METH_VARARGS,
         "Convert token flag to string"},
        {"dap_chain_datum_token_flag_from_str", dap_chain_datum_token_flag_from_str_py, METH_VARARGS,
         "Convert token flag from string"},
        {"dap_chain_datum_token_get_delegated_ticker", dap_chain_datum_token_get_delegated_ticker_py, METH_VARARGS,
         "Get delegated ticker from token ticker"},
        {"dap_chain_datum_token_is_old", dap_chain_datum_token_is_old_py, METH_VARARGS,
         "Check if token type is old"},
        {"dap_chain_datum_token_check_ticker", dap_chain_datum_token_check_ticker_py, METH_VARARGS,
         "Check token ticker validity"},
        {"dap_chain_datum_token_flags_dump_to_json", dap_chain_datum_token_flags_dump_to_json_py, METH_VARARGS,
         "Dump token flags to JSON"},
        {"dap_chain_datum_token_certs_dump", dap_chain_datum_token_certs_dump_py, METH_VARARGS,
         "Dump token certificates to string"},
        {"dap_chain_datum_token_certs_dump_to_json", dap_chain_datum_token_certs_dump_to_json_py, METH_VARARGS,
         "Dump token certificates to JSON"},
        {"dap_chain_datum_token_read", dap_chain_datum_token_read_py, METH_VARARGS,
         "Read token datum from serialized data"},
        {"dap_chain_datum_token_tsd_get", dap_chain_datum_token_tsd_get_py, METH_VARARGS,
         "Get token TSD pointer"},
        {"dap_chain_datum_emission_type_str", dap_chain_datum_emission_type_str_py, METH_VARARGS,
         "Convert emission type to string"},
        {"dap_chain_datum_emission_create", dap_chain_datum_emission_create_py, METH_VARARGS,
         "Create token emission"},
        {"dap_chain_datum_emission_add_tsd", dap_chain_datum_emission_add_tsd_py, METH_VARARGS,
         "Add TSD to emission"},
        {"dap_chain_emission_get_tsd", dap_chain_emission_get_tsd_py, METH_VARARGS,
         "Get emission TSD data"},
        {"dap_chain_datum_emission_get_size", dap_chain_datum_emission_get_size_py, METH_VARARGS,
         "Get emission size from serialized data"},
        {"dap_chain_datum_emission_read", dap_chain_datum_emission_read_py, METH_VARARGS,
         "Read emission from serialized data"},
        {"dap_chain_datum_emission_add_sign", dap_chain_datum_emission_add_sign_py, METH_VARARGS,
         "Add signature to emission"},
        {"dap_chain_datum_emission_append_sign", dap_chain_datum_emission_append_sign_py, METH_VARARGS,
         "Append signature to emission"},
        {"dap_chain_datum_emission_get_signs", dap_chain_datum_emission_get_signs_py, METH_VARARGS,
         "Get emission signatures"},
        {"dap_chain_datum_anchor_certs_dump", dap_chain_datum_anchor_certs_dump_py, METH_VARARGS,
         "Dump anchor certificates to string"},
        {"dap_chain_datum_anchor_certs_dump_json", dap_chain_datum_anchor_certs_dump_json_py, METH_VARARGS,
         "Dump anchor certificates to JSON"},
        {"dap_chain_datum_anchor_get_hash_from_data", dap_chain_datum_anchor_get_hash_from_data_py, METH_VARARGS,
         "Get anchor hash from data"},
        {"dap_chain_datum_anchor_get_size", dap_chain_datum_anchor_get_size_py, METH_VARARGS,
         "Get anchor datum size"},
        {"dap_chain_datum_from_tx", dap_chain_datum_from_tx_py, METH_VARARGS,
         "Convert transaction datum to datum"},
        {"dap_chain_datum_tx_event_to_json", dap_chain_datum_tx_event_to_json_py, METH_VARARGS,
         "Dump tx event to JSON"},
        {"dap_chain_datum_tx_item_event_to_json", dap_chain_datum_tx_item_event_to_json_py, METH_VARARGS,
         "Dump tx item event to JSON"},
        {"dap_chain_tx_item_event_type_from_str", dap_chain_tx_item_event_type_from_str_py, METH_VARARGS,
         "Convert tx event type from string"},
        {"dap_chain_tx_item_event_type_to_str", dap_chain_tx_item_event_type_to_str_py, METH_VARARGS,
         "Convert tx event type to string"},
        {"dap_chain_datum_item_tx_get_size", dap_chain_datum_item_tx_get_size_py, METH_VARARGS,
         "Get transaction item size"},
        {"dap_chain_datum_tx_event_create", dap_chain_datum_tx_event_create_py, METH_VARARGS,
         "Create tx event item"},
        {"dap_chain_datum_tx_item_get_data", dap_chain_datum_tx_item_get_data_py, METH_VARARGS,
         "Get tx item data"},
        {"dap_chain_datum_tx_item_get_tsd_by_type", dap_chain_datum_tx_item_get_tsd_by_type_py, METH_VARARGS,
         "Get tx TSD by type"},
        {"dap_chain_datum_tx_item_in_cond_create", dap_chain_datum_tx_item_in_cond_create_py, METH_VARARGS,
         "Create tx in_cond item"},
        {"dap_chain_datum_tx_item_in_create", dap_chain_datum_tx_item_in_create_py, METH_VARARGS,
         "Create tx in item"},
        {"dap_chain_datum_tx_item_in_ems_create", dap_chain_datum_tx_item_in_ems_create_py, METH_VARARGS,
         "Create tx in_ems item"},
        {"dap_chain_datum_tx_item_in_reward_create", dap_chain_datum_tx_item_in_reward_create_py, METH_VARARGS,
         "Create tx in_reward item"},
        {"dap_chain_datum_tx_item_out_cond_create_fee", dap_chain_datum_tx_item_out_cond_create_fee_py, METH_VARARGS,
         "Create out_cond fee item"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_pay", dap_chain_datum_tx_item_out_cond_create_srv_pay_py, METH_VARARGS,
         "Create out_cond service pay item"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_pay_with_hash", dap_chain_datum_tx_item_out_cond_create_srv_pay_with_hash_py, METH_VARARGS,
         "Create out_cond service pay item with hash"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_stake", dap_chain_datum_tx_item_out_cond_create_srv_stake_py, METH_VARARGS,
         "Create out_cond stake item"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_stake_delegate", dap_chain_datum_tx_item_out_cond_create_srv_stake_delegate_py, METH_VARARGS,
         "Create out_cond stake delegate item"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_stake_ext_lock", dap_chain_datum_tx_item_out_cond_create_srv_stake_ext_lock_py, METH_VARARGS,
         "Create out_cond stake ext lock item"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_stake_get_tsd_size", dap_chain_datum_tx_item_out_cond_create_srv_stake_get_tsd_size_py, METH_VARARGS,
         "Get out_cond stake TSD size"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_stake_lock", dap_chain_datum_tx_item_out_cond_create_srv_stake_lock_py, METH_VARARGS,
         "Create out_cond stake lock item"},
        {"dap_chain_datum_tx_item_out_cond_create_srv_xchange", dap_chain_datum_tx_item_out_cond_create_srv_xchange_py, METH_VARARGS,
         "Create out_cond xchange item"},
        {"dap_chain_datum_tx_item_out_cond_create_wallet_shared", dap_chain_datum_tx_item_out_cond_create_wallet_shared_py, METH_VARARGS,
         "Create out_cond wallet shared item"},
        {"dap_chain_datum_tx_item_out_create", dap_chain_datum_tx_item_out_create_py, METH_VARARGS,
         "Create out item"},
        {"dap_chain_datum_tx_item_out_ext_create", dap_chain_datum_tx_item_out_ext_create_py, METH_VARARGS,
         "Create out_ext item"},
        {"dap_chain_datum_tx_item_out_std_create", dap_chain_datum_tx_item_out_std_create_py, METH_VARARGS,
         "Create out_std item"},
        {"dap_chain_datum_tx_item_sig_get_sign", dap_chain_datum_tx_item_sig_get_sign_py, METH_VARARGS,
         "Get sign from tx sig item"},
        {"dap_chain_datum_tx_item_sign_create", dap_chain_datum_tx_item_sign_create_py, METH_VARARGS,
         "Create tx sig item"},
        {"dap_chain_datum_tx_item_sign_create_from_sign", dap_chain_datum_tx_item_sign_create_from_sign_py, METH_VARARGS,
         "Create tx sig item from sign"},
        {"dap_chain_datum_tx_item_tsd_create", dap_chain_datum_tx_item_tsd_create_py, METH_VARARGS,
         "Create tx TSD item"},
        {"dap_chain_datum_tx_item_type_from_str_short", dap_chain_datum_tx_item_type_from_str_short_py, METH_VARARGS,
         "Convert tx item type from short string"},
        {"dap_chain_datum_tx_item_type_to_str", dap_chain_datum_tx_item_type_to_str_py, METH_VARARGS,
         "Convert tx item type to string"},
        {"dap_chain_datum_tx_item_type_to_str_short", dap_chain_datum_tx_item_type_to_str_short_py, METH_VARARGS,
         "Convert tx item type to short string"},
        {"dap_chain_datum_tx_sign_create", dap_chain_datum_tx_sign_create_py, METH_VARARGS,
         "Create tx signature"},
        {"dap_chain_tx_event_copy", dap_chain_tx_event_copy_py, METH_VARARGS,
         "Copy tx event"},
        {"dap_chain_tx_event_delete", dap_chain_tx_event_delete_py, METH_VARARGS,
         "Delete tx event"},
        {"dap_chain_tx_out_cond_subtype_from_str_short", dap_chain_tx_out_cond_subtype_from_str_short_py, METH_VARARGS,
         "Convert out_cond subtype from short string"},
        {"dap_chain_tx_sig_create", dap_chain_tx_sig_create_py, METH_VARARGS,
         "Create tx sig item"},
        {"dap_chain_tx_out_cond_subtype_to_str", dap_chain_tx_out_cond_subtype_to_str_py, METH_VARARGS,
         "Convert out_cond subtype to string"},
        {"dap_chain_tx_out_cond_subtype_to_str_short", dap_chain_tx_out_cond_subtype_to_str_short_py, METH_VARARGS,
         "Convert out_cond subtype to short string"},
        {"dap_chain_datum_tx_receipt_check_size", dap_chain_datum_tx_receipt_check_size_py, METH_VARARGS,
         "Check tx receipt size"},
        {"dap_chain_datum_tx_receipt_create", dap_chain_datum_tx_receipt_create_py, METH_VARARGS,
         "Create tx receipt"},
        {"dap_chain_datum_tx_receipt_sign_add", dap_chain_datum_tx_receipt_sign_add_py, METH_VARARGS,
         "Add signature to tx receipt"},
        {"dap_chain_datum_tx_receipt_sign_get", dap_chain_datum_tx_receipt_sign_get_py, METH_VARARGS,
         "Get tx receipt signature"},
        {"dap_chain_datum_tx_receipt_signs_count", dap_chain_datum_tx_receipt_signs_count_py, METH_VARARGS,
         "Get tx receipt signatures count"},
        {"dap_chain_datum_tx_receipt_srv_uid_get", dap_chain_datum_tx_receipt_srv_uid_get_py, METH_VARARGS,
         "Get tx receipt service uid"},
        {"dap_chain_datum_tx_receipt_units_get", dap_chain_datum_tx_receipt_units_get_py, METH_VARARGS,
         "Get tx receipt units"},
        {"dap_chain_datum_tx_receipt_utype_get", dap_chain_datum_tx_receipt_utype_get_py, METH_VARARGS,
         "Get tx receipt unit type"},
        {"dap_chain_datum_tx_receipt_value_get", dap_chain_datum_tx_receipt_value_get_py, METH_VARARGS,
         "Get tx receipt value"},
        {"dap_chain_datum_tx_item_vote_create", dap_chain_datum_tx_item_vote_create_py, METH_VARARGS,
         "Create tx vote item"},
        {"dap_chain_datum_tx_item_vote_to_json", dap_chain_datum_tx_item_vote_to_json_py, METH_VARARGS,
         "Convert tx vote to JSON"},
        {"dap_chain_datum_tx_item_voting_create", dap_chain_datum_tx_item_voting_create_py, METH_VARARGS,
         "Create tx voting item"},
        {"dap_chain_datum_tx_item_voting_tsd_to_json", dap_chain_datum_tx_item_voting_tsd_to_json_py, METH_VARARGS,
         "Convert tx voting TSD to JSON"},
        {"dap_chain_datum_tx_voting_get_answer_text_by_idx", dap_chain_datum_tx_voting_get_answer_text_by_idx_py, METH_VARARGS,
         "Get voting answer text by index"},
        {"dap_chain_datum_tx_voting_params_delete", dap_chain_datum_tx_voting_params_delete_py, METH_VARARGS,
         "Delete voting params"},
        {"dap_chain_datum_tx_voting_parse_tsd", dap_chain_datum_tx_voting_parse_tsd_py, METH_VARARGS,
         "Parse voting params from tx"},
        {"dap_chain_datum_voting_answer_tsd_create", dap_chain_datum_voting_answer_tsd_create_py, METH_VARARGS,
         "Create voting answer TSD"},
        {"dap_chain_datum_voting_cancel_tsd_create", dap_chain_datum_voting_cancel_tsd_create_py, METH_VARARGS,
         "Create voting cancel TSD"},
        {"dap_chain_datum_voting_delegated_key_required_tsd_create", dap_chain_datum_voting_delegated_key_required_tsd_create_py, METH_VARARGS,
         "Create voting delegated key required TSD"},
        {"dap_chain_datum_voting_expire_tsd_create", dap_chain_datum_voting_expire_tsd_create_py, METH_VARARGS,
         "Create voting expire TSD"},
        {"dap_chain_datum_voting_max_votes_count_tsd_create", dap_chain_datum_voting_max_votes_count_tsd_create_py, METH_VARARGS,
         "Create voting max votes count TSD"},
        {"dap_chain_datum_voting_question_tsd_create", dap_chain_datum_voting_question_tsd_create_py, METH_VARARGS,
         "Create voting question TSD"},
        {"dap_chain_datum_voting_token_tsd_create", dap_chain_datum_voting_token_tsd_create_py, METH_VARARGS,
         "Create voting token TSD"},
        {"dap_chain_datum_voting_vote_changing_allowed_tsd_create", dap_chain_datum_voting_vote_changing_allowed_tsd_create_py, METH_VARARGS,
         "Create voting vote changing allowed TSD"},
        {"dap_chain_datum_voting_vote_tx_cond_tsd_create", dap_chain_datum_voting_vote_tx_cond_tsd_create_py, METH_VARARGS,
         "Create voting vote tx cond TSD"},
        {"dap_chain_datum_decree_certs_dump_json", dap_chain_datum_decree_certs_dump_json_py, METH_VARARGS,
         "Dump decree certificates to JSON"},
        {"dap_chain_datum_decree_dump_json", dap_chain_datum_decree_dump_json_py, METH_VARARGS,
         "Dump decree to JSON"},
        {"dap_chain_datum_decree_get_action", dap_chain_datum_decree_get_action_py, METH_VARARGS,
         "Get decree action"},
        {"dap_chain_datum_decree_get_atom_num", dap_chain_datum_decree_get_atom_num_py, METH_VARARGS,
         "Get decree atom number"},
        {"dap_chain_datum_decree_get_ban_addr", dap_chain_datum_decree_get_ban_addr_py, METH_VARARGS,
         "Get decree ban address"},
        {"dap_chain_datum_decree_get_empty_block_every_times", dap_chain_datum_decree_get_empty_block_every_times_py, METH_VARARGS,
         "Get decree empty block generation period"},
        {"dap_chain_datum_decree_get_fee", dap_chain_datum_decree_get_fee_py, METH_VARARGS,
         "Get decree fee value"},
        {"dap_chain_datum_decree_get_fee_addr", dap_chain_datum_decree_get_fee_addr_py, METH_VARARGS,
         "Get decree fee address"},
        {"dap_chain_datum_decree_get_hash", dap_chain_datum_decree_get_hash_py, METH_VARARGS,
         "Get decree hash"},
        {"dap_chain_datum_decree_get_min_owners", dap_chain_datum_decree_get_min_owners_py, METH_VARARGS,
         "Get decree minimum owners"},
        {"dap_chain_datum_decree_get_node_addr", dap_chain_datum_decree_get_node_addr_py, METH_VARARGS,
         "Get decree node address"},
        {"dap_chain_datum_decree_get_owners", dap_chain_datum_decree_get_owners_py, METH_VARARGS,
         "Get decree owners list"},
        {"dap_chain_datum_decree_get_pkey", dap_chain_datum_decree_get_pkey_py, METH_VARARGS,
         "Get decree public key"},
        {"dap_chain_datum_decree_get_policy", dap_chain_datum_decree_get_policy_py, METH_VARARGS,
         "Get decree policy"},
        {"dap_chain_datum_decree_get_signature_type", dap_chain_datum_decree_get_signature_type_py, METH_VARARGS,
         "Get decree signature type"},
        {"dap_chain_datum_decree_get_signs", dap_chain_datum_decree_get_signs_py, METH_VARARGS,
         "Get decree signs"},
        {"dap_chain_datum_decree_get_size", dap_chain_datum_decree_get_size_py, METH_VARARGS,
         "Get decree size"},
        {"dap_chain_datum_decree_get_stake_min_signers_count", dap_chain_datum_decree_get_stake_min_signers_count_py, METH_VARARGS,
         "Get decree stake min signers count"},
        {"dap_chain_datum_decree_get_stake_min_value", dap_chain_datum_decree_get_stake_min_value_py, METH_VARARGS,
         "Get decree stake min value"},
        {"dap_chain_datum_decree_get_stake_signing_addr", dap_chain_datum_decree_get_stake_signing_addr_py, METH_VARARGS,
         "Get decree stake signing address"},
        {"dap_chain_datum_decree_get_stake_value", dap_chain_datum_decree_get_stake_value_py, METH_VARARGS,
         "Get decree stake value"},
        {"dap_chain_datum_decree_get_value", dap_chain_datum_decree_get_value_py, METH_VARARGS,
         "Get decree value"},
        {"dap_chain_datum_decree_new", dap_chain_datum_decree_new_py, METH_VARARGS,
         "Create new decree"},
        {"dap_chain_datum_decree_sign_in_cycle", dap_chain_datum_decree_sign_in_cycle_py, METH_VARARGS,
         "Sign decree in cycle"},
        {"dap_chain_datum_decree_subtype_to_str", dap_chain_datum_decree_subtype_to_str_py, METH_VARARGS,
         "Convert decree subtype to string"},
        {"dap_chain_datum_decree_tsd_type_to_str", dap_chain_datum_decree_tsd_type_to_str_py, METH_VARARGS,
         "Convert decree TSD type to string"},
        {"dap_chain_datum_decree_type_from_str", dap_chain_datum_decree_type_from_str_py, METH_VARARGS,
         "Convert decree type from string"},
        {"dap_chain_decree_registry_deinit", dap_chain_decree_registry_deinit_py, METH_VARARGS,
         "Deinitialize decree registry"},
        {"dap_chain_decree_registry_has_handler", dap_chain_decree_registry_has_handler_py, METH_VARARGS,
         "Check decree registry handler"},
        {"dap_chain_decree_registry_init", dap_chain_decree_registry_init_py, METH_VARARGS,
         "Initialize decree registry"},
        {"dap_chain_decree_registry_process", dap_chain_decree_registry_process_py, METH_VARARGS,
         "Process decree via registry"},
        {"dap_chain_decree_registry_register_handler", dap_chain_decree_registry_register_handler_py, METH_VARARGS,
         "Register decree handler"},
        {"dap_chain_decree_registry_unregister_handler", dap_chain_decree_registry_unregister_handler_py, METH_VARARGS,
         "Unregister decree handler"},
        {NULL, NULL, 0, NULL}
    };

    for (PyMethodDef *method = datum_methods; method->ml_name != NULL; method++) {
        PyObject *func = PyCFunction_New(method, NULL);
        if (!func) {
            return -1;
        }
        if (PyModule_AddObject(module, method->ml_name, func) < 0) {
            Py_DECREF(func);
            return -1;
        }
    }

    return 0;
}
